# Generated by Django 6.0.5 on 2026-05-31 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boloes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servidor_smtp', models.CharField(max_length=200, verbose_name='Servidor SMTP')),
                ('porta', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('usuario_email', models.EmailField(max_length=254, verbose_name='Usuário de e-mail')),
                ('senha_email', models.CharField(max_length=200, verbose_name='Senha do e-mail')),
                ('usar_tls', models.BooleanField(default=True, verbose_name='Usar TLS')),
                ('email_remetente', models.EmailField(max_length=254, verbose_name='E-mail remetente')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Configuração de E-mail',
                'verbose_name_plural': 'Configurações de E-mail',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoPixAdministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], max_length=20, verbose_name='Tipo de chave')),
                ('chave_pix', models.CharField(max_length=150, verbose_name='Chave Pix')),
                ('nome_recebedor', models.CharField(max_length=100, verbose_name='Nome do recebedor')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('documento_recebedor', models.CharField(max_length=20, verbose_name='Documento (CPF/CNPJ)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Configuração Pix do Administrador',
                'verbose_name_plural': 'Configurações Pix do Administrador',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('expirado', 'Expirado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('txid', models.CharField(blank=True, max_length=100, verbose_name='ID da transação')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code (base64)')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('participacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='boloes.participacaobolao', verbose_name='Participação')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
