# Generated by Django 6.0.5 on 2026-05-31 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_efi_bank_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total (R$)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('expirado', 'Expirado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('txid', models.CharField(blank=True, max_length=100, unique=True, verbose_name='ID da transação (lote)')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code (base64)')),
                ('pix_copia_cola', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Expira em')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_pagamento', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pagamento em lote',
                'verbose_name_plural': 'Pagamentos em lote',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='pagamento',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='pagamentos.pagamentolote', verbose_name='Lote de pagamento'),
        ),
    ]
