# Generated by Django 6.0.5 on 2026-05-31 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('bandeira', models.ImageField(blank=True, null=True, upload_to='bandeiras/', verbose_name='Bandeira')),
                ('icone', models.CharField(blank=True, max_length=10, verbose_name='Ícone (emoji)')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e hora da partida')),
                ('estadio', models.CharField(blank=True, max_length=150, verbose_name='Estádio')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('oitavas', 'Oitavas de Final'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('terceiro', 'Disputa 3º lugar'), ('final', 'Final')], default='grupos', max_length=20, verbose_name='Fase')),
                ('status', models.CharField(choices=[('agendado', 'Agendada'), ('aberto', 'Aberta para bolão'), ('bloqueado', 'Bloqueada para apostas'), ('andamento', 'Em andamento'), ('encerrado', 'Encerrada'), ('resultado', 'Resultado informado'), ('premiacao', 'Premiação gerada'), ('pago', 'Pagamentos realizados')], default='agendado', max_length=20, verbose_name='Status')),
                ('placar_mandante', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Placar mandante')),
                ('placar_visitante', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Placar visitante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('selecao_mandante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_mandante', to='jogos.selecao', verbose_name='Seleção mandante')),
                ('selecao_visitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_visitante', to='jogos.selecao', verbose_name='Seleção visitante')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['data_hora'],
            },
        ),
    ]
