# Generated by Django 6.0.5 on 2026-06-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoCampeao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da sessão')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Navegador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_campeao', to='jogos.selecao', verbose_name='Seleção campeã')),
            ],
            options={
                'verbose_name': 'Voto da enquete',
                'verbose_name_plural': 'Votos da enquete',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
