# Generated by Django 6.0.5 on 2026-05-31 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status do pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('comprovante', models.TextField(blank=True, verbose_name='Comprovante')),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
            },
        ),
        migrations.CreateModel(
            name='Bolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do bolão')),
                ('valor_participacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de participação (R$)')),
                ('percentual_premiacao', models.PositiveSmallIntegerField(default=70, help_text='De 0 a 100%', verbose_name='Percentual de premiação (%)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Aberto'), ('fechado', 'Fechado'), ('encerrado', 'Encerrado'), ('premiacao', 'Premiação gerada'), ('pago', 'Pagamentos realizados')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_abertura', models.DateTimeField(blank=True, null=True, verbose_name='Data de abertura')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de fechamento')),
                ('regra_sem_ganhador', models.CharField(choices=[('acumular', 'Acumular para próximo bolão'), ('devolver', 'Devolver aos participantes'), ('reter', 'Manter valor retido')], default='acumular', max_length=20, verbose_name='Regra sem ganhador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boloes', to='jogos.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Bolão',
                'verbose_name_plural': 'Bolões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoBolao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('placar_mandante', models.PositiveSmallIntegerField(verbose_name='Placar mandante')),
                ('placar_visitante', models.PositiveSmallIntegerField(verbose_name='Placar visitante')),
                ('data_palpite', models.DateTimeField(auto_now_add=True, verbose_name='Data do palpite')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('expirado', 'Pagamento expirado'), ('confirmado', 'Pagamento confirmado'), ('valido', 'Palpite válido'), ('vencedor', 'Palpite vencedor'), ('nao_premiado', 'Palpite não premiado'), ('premio_pago', 'Pagamento do prêmio realizado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('bloqueado_para_edicao', models.BooleanField(default=True, verbose_name='Bloqueado para edição')),
                ('bolao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to='boloes.bolao', verbose_name='Bolão')),
            ],
            options={
                'verbose_name': 'Participação',
                'verbose_name_plural': 'Participações',
                'ordering': ['-data_palpite'],
            },
        ),
    ]
