# Generated by Django 6.0.5 on 2026-05-31 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boloes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaobolao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='premio',
            name='bolao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='boloes.bolao', verbose_name='Bolão'),
        ),
        migrations.AddField(
            model_name='premio',
            name='participacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to='boloes.participacaobolao', verbose_name='Participação'),
        ),
        migrations.AddField(
            model_name='premio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='premios', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
