# Generated by Django 6.0.5 on 2026-05-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
