# Generated by Django 6.0.5 on 2026-06-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_telefone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
    ]
