# Generated by Django 6.0.5 on 2026-05-31 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PixUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chave', models.CharField(choices=[('cpf', 'CPF'), ('telefone', 'Telefone'), ('email', 'E-mail'), ('aleatoria', 'Chave aleatória')], max_length=20, verbose_name='Tipo de chave')),
                ('chave_pix', models.CharField(max_length=150, verbose_name='Chave Pix')),
                ('nome_recebedor', models.CharField(max_length=100, verbose_name='Nome do recebedor')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pix do usuário',
                'verbose_name_plural': 'Pix dos usuários',
            },
        ),
    ]
